### ISSUE TITLE
changing legend ax

### ISSUE THREAD

**Issue by liliblu** [schlegelp/catheat#8]
I was wondering if there is a way to either change the ax on which the legend will be drawn, or grab the handles without creating a legend to make one from scratch? Is there a way to access the category: color assignments made automatically without drawing a legend?
Thank you!

**Comment by schlegelp** [comment]
Hi @liliblu. That's a good question. There currently is no easy way of doing this but I will add both these features.

**Comment by schlegelp** [comment]
I just pushed a new version (0.2.0) to Github. The relevant changes for you are:
- you can now explicitly provide an ax for the legend via the `leg_ax` parameter and other keyword arguments via `leg_kws`
- `heatmap` now returns a tuple: `(heatmap axis, colormap dictionary)`

Let me know if this is what you were looking for

**Comment by liliblu** [comment]
That is perfect! Thank you so much!
